# Build program
program: 
	cd ./main; make main

silent:
	cd ./main; make silent

# Run program
run:
	cd ./main; make run

# Clean up
clean:
	cd ./main; make clean_all

log_peek:
	cd ./main; cat log.txt